### ISSUE TITLE
Random Errors in our logs

### ISSUE THREAD

**Issue by davglass** [davglass/registry-static#11]
Here are some random errors in our local logs:

```
[Error: Hostname/IP doesn't match certificate's altnames]

SyntaxError: Unexpected token <
    at Object.parse (native)
    at Object.patchPath [as json] (/home/davglass/registry-static/node_modules/patch-package-json/patch.js:28:21)
    at Object.change [as handler] (/home/davglass/registry-static/lib/index.js:79:22)
    at /home/davglass/registry-static/node_modules/follow-registry/lib/index.js:20:24
    at Request._callback (/home/davglass/registry-static/node_modules/follow-registry/lib/registry.js:24:9)
    at Request.self.callback (/home/davglass/registry-static/node_modules/request/request.js:372:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/home/davglass/registry-static/node_modules/request/request.js:1317:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/davglass/registry-static/node_modules/request/request.js:1265:12)
{ [Error: getaddrinfo ENOTFOUND] code: 'ENOTFOUND', errno: 'ENOTFOUND', syscall: 'getaddrinfo' }
```

These are from our `nohup` log, so it's a bit hard to track. I think the first error and the last are from `request` and the registry. The other error is totally from my `patch-package-json` module.

**Comment by davglass** [comment]
#17 fixes the syntax error, but I think we should add the [dnscache](https://www.npmjs.com/package/dnscache) to the `lib/background.js` file so that DNS lookups on each request get's cached. Which is where I believe the `getaddrinfo ENOTFOUND` error comes from.

**Comment by bengl** [comment]
Maybe should close this since it's basically #10 + #17 ?
