### ISSUE TITLE
Semver sanitization

### ISSUE THREAD

**Issue by krotscheck** [davglass/registry-static#68]
So, we just ran into the following:

```
> npm install --verbose shelljs@0.0.1alpha1

npm info it worked if it ends with ok
npm verb cli [ '/usr/local/Cellar/node4-lts/4.4.2/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'shelljs@0.0.1alpha1' ]
npm info using npm@3.8.5
npm info using node@v4.4.2
npm verb request uri http://mirror.dfw.rax.openstack.org/npm/shelljs
npm verb request no auth needed
npm info attempt registry request try #1 at 9:26:53 AM
npm verb request id 33270f960f7e5277
npm verb etag "1685e-530d28b5dd0c0"
npm verb lastModified Tue, 19 Apr 2016 08:48:43 GMT
npm http request GET http://mirror.dfw.rax.openstack.org/npm/shelljs
npm http 304 http://mirror.dfw.rax.openstack.org/npm/shelljs
npm verb headers { date: 'Fri, 22 Apr 2016 16:26:53 GMT',
npm verb headers   server: 'Apache/2.4.7 (Ubuntu)',
npm verb headers   connection: 'Keep-Alive',
npm verb headers   'keep-alive': 'timeout=5, max=99',
npm verb headers   etag: '"1685e-530d28b5dd0c0"' }
npm verb etag http://mirror.dfw.rax.openstack.org/npm/shelljs from cache
npm verb get saving shelljs to /Users/krotscheck/.npm/mirror.dfw.rax.openstack.org/npm/shelljs/.cache.json
npm verb correctMkdir /Users/krotscheck/.npm correctMkdir not in flight; initializing
npm verb stack TypeError: Invalid Version: 0.0.1alpha1
npm verb stack     at new SemVer (/usr/local/lib/node_modules/npm/node_modules/semver/semver.js:293:11)
npm verb stack     at SemVer.compare (/usr/local/lib/node_modules/npm/node_modules/semver/semver.js:342:13)
npm verb stack     at compare (/usr/local/lib/node_modules/npm/node_modules/semver/semver.js:566:31)
npm verb stack     at rcompare (/usr/local/lib/node_modules/npm/node_modules/semver/semver.js:576:10)
npm verb stack     at Array.sort (native)
npm verb stack     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:121:48)
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
npm verb stack     at /usr/local/lib/node_modules/npm/lib/utils/pulse-till-done.js:19:8
npm verb stack     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:168:7)
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
npm verb cwd /Users/krotscheck/Desktop/openstack/horizon
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node4-lts/4.4.2/bin/node" "/usr/local/bin/npm" "install" "--verbose" "shelljs@0.0.1alpha1"
npm ERR! node v4.4.2
npm ERR! npm  v3.8.5

npm ERR! Invalid Version: 0.0.1alpha1
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/krotscheck/Desktop/openstack/horizon/npm-debug.log`
```

A bit of sleuthing lead me to https://github.com/npm/npm/issues/9701, which suggests that some of the older packages will have versioning problems. Practically speaking they may not cause that many issues, since they're so old and the dependencies should have been updated, however it might be something worth fixing. I'm building a list of all impacted packages now.

**Comment by krotscheck** [comment]
The reason I'm bringing this up is that our version of registry-static is 2.2.0, the most recent one. I get that @bengl commented on that, but something might still be going on?

**Comment by krotscheck** [comment]
Investigated more, it's our own rewrite rules. My bad :/
