### ISSUE TITLE
TypeError: Cannot read property 'emit' of null

### ISSUE THREAD

**Issue by xloem** [davglass/registry-static#74]
I'm getting this error on every run:

```
_http_client.js:277       
  req.emit('close');      
     ^                    

TypeError: Cannot read property 'emit' of null      
    at TLSSocket.socketCloseListener (_http_client.js:277:6)                                            
    at emitOne (events.js:101:20)                   
    at TLSSocket.emit (events.js:188:7)             
    at _handle.close (net.js:509:12)                
    at TCP.done [as _onclose] (_tls_wrap.js:332:7)  
```

**Comment by xloem** [comment]
https://github.com/nodejs/node/issues/20690

**Comment by xloem** [comment]
I learned of `NODE_DEBUG=http,net` and got this immediately prior to the above error:
```
NET 5525: destroy undefined                         
NET 5525: destroy                                                                                       
NET 5525: close                                     
NET 5525: close handle                              
NET 5525: emit close      
HTTP 5525: HTTP socket close                        
NET 5525: _read           
NET 5525: _read wait for connection                 
```

**Comment by xloem** [comment]
node.js is on top of this as linked above.  it's theoretically been fixed in git master.
